name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: ./Crane
      - name: Create secrets
        env:
          API_KEY_PIXABAY: ${{ secrets.API_KEY_PIXABAY }}
          API_KEY_FOURSQUARE: ${{ secrets.API_KEY_FOURSQUARE }}
        run: |
          echo API_KEY_PIXABAY=\"$API_KEY_PIXABAY\" > ./local.properties
          echo API_KEY_FOURSQUARE=\"$API_KEY_FOURSQUARE\" > ./local.properties
      - name: Build with Gradle
        run: ./gradlew build
        working-directory: ./Crane
